/* EpwWeatherWriter.cs
 *
 * Copyright (C) 2026 E.Togashi
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or (at
 * your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

using System;
using System.Globalization;
using System.IO;
using Popolo.Core.Climate.Weather;
using Popolo.Core.Exceptions;
using Popolo.Core.Physics;

namespace Popolo.IO.Climate.Weather
{
  /// <summary>
  /// Writes <see cref="IReadOnlyWeatherData"/> in EnergyPlus Weather (EPW)
  /// format.
  /// </summary>
  /// <remarks>
  /// <para>
  /// Output is an 8-line header followed by hourly data lines. Date labels
  /// on the hour=24 records (the last hour of each day) use the date of the
  /// **current** day (the day that is ending), which follows the canonical
  /// EPW convention and avoids the "Feb 31" style labels that some legacy
  /// writers produced.
  /// </para>
  /// <para>
  /// Fields that are not recorded in the source data are written using EPW
  /// missing-value sentinels (9999 / 99 / 999 / 999999 / etc.) so that the
  /// output file remains syntactically valid for EnergyPlus. The dew-point
  /// and relative-humidity fields are re-derived from dry-bulb, absolute
  /// humidity, and pressure via <see cref="MoistAir"/>.
  /// </para>
  /// <para>
  /// Data source tags (column 5) and constant-like uncertainty fields
  /// (illuminance, present weather, etc.) are written with generic
  /// placeholders; consumers that rely on those fields should post-process
  /// the output.
  /// </para>
  /// </remarks>
  public class EpwWeatherWriter : IWeatherDataWriter
  {
    /// <summary>Country code written to the LOCATION header. Default "XXX".</summary>
    public string CountryCode { get; set; } = "XXX";

    /// <summary>Region label written to the LOCATION header. Default empty.</summary>
    public string Region { get; set; } = "";

    /// <summary>Data source label written to the LOCATION header.</summary>
    public string DataSourceLabel { get; set; } = "Popolo";

    /// <summary>WMO station number. Default 0 (unknown).</summary>
    public int WmoNumber { get; set; }

    /// <summary>Time zone offset from UTC [hours]. Default 0.</summary>
    public double TimeZone { get; set; }

    /// <inheritdoc />
    public void Write(IReadOnlyWeatherData data, string path)
    {
      if (data == null) throw new PopoloArgumentException("data must not be null.", nameof(data));
      if (string.IsNullOrEmpty(path))
        throw new PopoloArgumentException("path must not be null or empty.", nameof(path));
      using var stream = new FileStream(path, FileMode.Create, FileAccess.Write, FileShare.None);
      Write(data, stream);
    }

    /// <inheritdoc />
    public void Write(IReadOnlyWeatherData data, Stream stream)
    {
      if (data == null) throw new PopoloArgumentException("data must not be null.", nameof(data));
      if (stream == null) throw new PopoloArgumentException("stream must not be null.", nameof(stream));

      using var writer = new StreamWriter(stream, new System.Text.UTF8Encoding(false), 1024, leaveOpen: true);
      WriteCore(data, writer);
      writer.Flush();
    }

    private void WriteCore(IReadOnlyWeatherData data, TextWriter writer)
    {
      var ci = CultureInfo.InvariantCulture;
      var station = data.Station;

      // --- 8 行のヘッダ ---
      string name = string.IsNullOrEmpty(station.Name) ? "UNKNOWN" : station.Name;
      writer.WriteLine(string.Format(ci,
          "LOCATION,{0},{1},{2},{3},{4},{5:F2},{6:F2},{7:F1},{8:F1}",
          Escape(name), Escape(Region), CountryCode, Escape(DataSourceLabel),
          WmoNumber, station.Latitude, station.Longitude, TimeZone, station.Elevation));
      writer.WriteLine("DESIGN CONDITIONS,0");
      writer.WriteLine("TYPICAL/EXTREME PERIODS,0");
      writer.WriteLine("GROUND TEMPERATURES,0");
      writer.WriteLine("HOLIDAYS/DAYLIGHT SAVINGS,No,0,0,0");
      writer.WriteLine("COMMENTS 1,Generated by Popolo");
      writer.WriteLine("COMMENTS 2,");
      writer.WriteLine(string.Format(ci,
          "DATA PERIODS,1,1,Data,Sunday,{0}/{1},{2}/{3}",
          data.Count > 0 ? data.Records[0].Time.Month : 1,
          data.Count > 0 ? data.Records[0].Time.Day : 1,
          data.Count > 0 ? data.Records[data.Count - 1].Time.Month : 12,
          data.Count > 0 ? data.Records[data.Count - 1].Time.Day : 31));

      // --- データ行 ---
      // EPW convention: hour field is 1..24. hour=24 represents the hour
      // ending at midnight of the labelled day (i.e. last hour of that day).
      // A Popolo record whose Time is 23:00 is the last hour of that day, and
      // is written as hour=24 with the SAME day label (EPW canonical).
      foreach (var r in data.Records)
      {
        DateTime t = r.Time;
        int epwHour = t.Hour + 1;  // 0..23 → 1..24
        int monthLabel = t.Month;
        int dayLabel = t.Day;
        // TMY では年カラムに元観測年 (SourceTime.Year) を書き、IsTypicalYear が
        // 再読込時に復元されるようにする。通常データでは SourceTime == Time のため
        // 結果は同じ。
        int yearLabel = r.SourceTime != default ? r.SourceTime.Year : t.Year;

        // データソース列 (固定プレースホルダ)
        writer.Write(string.Format(ci, "{0},{1},{2},{3},60,?0?0?0?0?0?0?0?0?0?0?0?0?0?0?0?0?0?0?0?0?0?0",
            yearLabel, monthLabel, dayLabel, epwHour));

        // [6] 乾球温度 [°C], 欠測99.9
        writer.Write(',');
        writer.Write(r.Has(WeatherField.DryBulbTemperature)
            ? r.DryBulbTemperature.ToString("F1", ci) : "99.9");

        // [7] 露点温度 [°C] は絶対湿度+気圧から逆算
        double pressureKPa = r.Has(WeatherField.AtmosphericPressure)
            ? r.AtmosphericPressure : PhysicsConstants.StandardAtmosphericPressure;
        string dewPoint = "99.9";
        string relHumidity = "999";
        if (r.Has(WeatherField.DryBulbTemperature) && r.Has(WeatherField.HumidityRatio))
        {
          double hrKgKg = r.HumidityRatio * 1.0e-3;
          try
          {
            double dp = MoistAir.GetDryBulbTemperatureFromHumidityRatioAndRelativeHumidity(
                hrKgKg, 100.0, pressureKPa);
            dewPoint = dp.ToString("F1", ci);
            double rh = MoistAir.GetRelativeHumidityFromDryBulbTemperatureAndHumidityRatio(
                r.DryBulbTemperature, hrKgKg, pressureKPa);
            relHumidity = ((int)Math.Round(Math.Max(0, Math.Min(100, rh)))).ToString(ci);
          }
          catch
          {
            // 物理的に不整合な場合は欠測記号を残す
          }
        }
        writer.Write(',');
        writer.Write(dewPoint);
        writer.Write(',');
        writer.Write(relHumidity);

        // [9] 気圧 [Pa], 欠測999999
        writer.Write(',');
        writer.Write(r.Has(WeatherField.AtmosphericPressure)
            ? ((int)Math.Round(r.AtmosphericPressure * 1000.0)).ToString(ci) : "999999");

        // [10..11] 外気圏上水平/法線日射 (未サポート) → 9999
        writer.Write(",9999,9999");

        // [12] 大気放射量 [W/m²], 欠測9999
        writer.Write(',');
        writer.Write(r.Has(WeatherField.AtmosphericRadiation)
            ? ((int)Math.Round(r.AtmosphericRadiation)).ToString(ci) : "9999");

        // [13] 全天日射
        writer.Write(',');
        writer.Write(r.Has(WeatherField.GlobalHorizontalRadiation)
            ? ((int)Math.Round(r.GlobalHorizontalRadiation)).ToString(ci) : "9999");

        // [14] 直達日射
        writer.Write(',');
        writer.Write(r.Has(WeatherField.DirectNormalRadiation)
            ? ((int)Math.Round(r.DirectNormalRadiation)).ToString(ci) : "9999");

        // [15] 天空日射
        writer.Write(',');
        writer.Write(r.Has(WeatherField.DiffuseHorizontalRadiation)
            ? ((int)Math.Round(r.DiffuseHorizontalRadiation)).ToString(ci) : "9999");

        // [16..19] 照度 4 項目 (未サポート)
        writer.Write(",999999,999999,999999,9999");

        // [20] 風向 [deg]
        writer.Write(',');
        if (r.Has(WeatherField.WindDirection))
        {
          // Popolo rad (南基準, 東負, 西正) → EPW deg (北基準, 時計回り)
          double degFromSouth = r.WindDirection * 180.0 / Math.PI;
          double bearing = degFromSouth + 180.0;
          while (bearing >= 360.0) bearing -= 360.0;
          while (bearing < 0.0) bearing += 360.0;
          writer.Write(((int)Math.Round(bearing)).ToString(ci));
        }
        else writer.Write("999");

        // [21] 風速 [m/s]
        writer.Write(',');
        writer.Write(r.Has(WeatherField.WindSpeed)
            ? r.WindSpeed.ToString("F1", ci) : "999");

        // [22] 全天雲量 [0..10]
        writer.Write(',');
        writer.Write(r.Has(WeatherField.CloudCover)
            ? ((int)Math.Round(r.CloudCover * 10.0)).ToString(ci) : "99");

        // [23] 不透明雲量 (未サポート) → 99
        writer.Write(",99");

        // [24..32] 視程、雲高、気象コード、可降水量、大気光学厚、積雪、降雪日数、地表反射率
        writer.Write(",9999,99999,9,999999999,999,.999,999,99,999");

        // [33] 降水量 [mm]
        writer.Write(',');
        writer.Write(r.Has(WeatherField.Precipitation)
            ? r.Precipitation.ToString("F1", ci) : "999");

        // [34] 降水時間 (未サポート)
        writer.Write(",99");

        writer.WriteLine();
      }
    }

    private static string Escape(string s)
    {
      if (string.IsNullOrEmpty(s)) return "";
      return s.Replace(',', ' ').Replace('\r', ' ').Replace('\n', ' ');
    }
  }
}
